"""Add last_viewed and adjust views for recipes

Revision ID: 19bc37fee45f
Revises: 
Create Date: 2024-09-02 11:17:15.478089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19bc37fee45f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_viewed', sa.DateTime(), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('last_viewed')

    # ### end Alembic commands ###
