"""Initial migration

Revision ID: 89e53d1fc24f
Revises:
Create Date: 2024-09-29 13:59:10.539697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e53d1fc24f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                            sa.Column('recipe_id', sa.Integer(), nullable=False),
                            sa.Column('recipe_title', sa.String(length=200), nullable=False),
                            sa.Column('recipe_image', sa.String(length=200), nullable=False),
                            sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                            sa.Column('title', sa.String(length=200), nullable=False),
                            sa.Column('description', sa.Text(), nullable=True),
                            sa.Column('serves', sa.String(length=50), nullable=True),
                            sa.Column('prep_time', sa.String(length=50), nullable=True),
                            sa.Column('cook_time', sa.String(length=50), nullable=True),
                            sa.Column('age_group', sa.String(length=50), nullable=True),
                            sa.Column('ingredients', sa.Text(), nullable=True),
                            sa.Column('method', sa.Text(), nullable=True),
                            sa.Column('url', sa.String(length=200), nullable=True),
                            sa.Column('image_url', sa.String(length=200), nullable=True),
                            sa.Column('views', sa.Integer(), nullable=True),
                            sa.Column('last_viewed', sa.DateTime(), nullable=True),
                            sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                            sa.Column('profile_image', sa.String(length=100), nullable=True),
                            sa.Column('username', sa.String(length=100), nullable=False),
                            sa.Column('first_name', sa.String(length=100), nullable=False),
                            sa.Column('last_name', sa.String(length=100), nullable=False),
                            sa.Column('email', sa.String(length=100), nullable=False),
                            sa.Column('password', sa.String(length=100), nullable=False),
                            sa.PrimaryKeyConstraint('id'),
                            sa.UniqueConstraint('username')
    )
    op.create_table('meal_plan',
                    sa.Column('id', sa.Integer(), nullable=False),
                            sa.Column('name', sa.String(length=100), nullable=False),
                            sa.Column('user_id', sa.Integer(), nullable=False),
                            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                            sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_favourites',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                            sa.Column('favourite_id', sa.Integer(), nullable=False),
                            sa.ForeignKeyConstraint(['favourite_id'], ['favourites.id'], ),
                            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                            sa.PrimaryKeyConstraint('user_id', 'favourite_id')
    )
    op.create_table('meal_plan_day',
                    sa.Column('id', sa.Integer(), nullable=False),
                            sa.Column('day', sa.String(length=10), nullable=False),
                            sa.Column('meal_plan_id', sa.Integer(), nullable=False),
                            sa.Column('breakfast_id', sa.Integer(), nullable=True),
                            sa.Column('lunch_id', sa.Integer(), nullable=True),
                            sa.Column('dinner_id', sa.Integer(), nullable=True),
                            sa.ForeignKeyConstraint(['breakfast_id'], ['recipes.id'], ),
                            sa.ForeignKeyConstraint(['dinner_id'], ['recipes.id'], ),
                            sa.ForeignKeyConstraint(['lunch_id'], ['recipes.id'], ),
                            sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plan.id'], ),
                            sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plan_recipes',
                    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
                            sa.Column('recipe_id', sa.Integer(), nullable=False),
                            sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plan.id'], ),
                            sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
                            sa.PrimaryKeyConstraint('meal_plan_id', 'recipe_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_plan_recipes')
    op.drop_table('meal_plan_day')
    op.drop_table('user_favourites')
    op.drop_table('meal_plan')
    op.drop_table('users')
    op.drop_table('recipes')
    op.drop_table('favourites')
    # ### end Alembic commands ###
